channels:
  global:
    default: true
    format: "%vault_prefix% &f%player_name% &7>"
    permission: "none"
    autoJoin: true
    command: "globalchannel"
  vip:
    format: "&e&lVIP &c&l| &f%player_name% &7>"
    color: "red"
    permission: "magicchat.channels.vip"
    autoJoin: true
    command: "vipchannel"
  staff:
    format: "&4&lSTAFF &c&l| &f%player_name% &7>"
    color: "&b"
    permission: "magicchat.channels.staff"
    autoJoin: true
    command: "staffchannel"
  network:
    format: "&b&lNETWORK &c&l| &f%player_name% &7>"
    color: "aqua"
    permission: "magicchat.channels.network"
    autoJoin: true
    command: "networkchannel"
    bungee: true
joinMessage:
  enable: true
  message: "&b%player_name% &eIngreso al servidor!"
quitMessage:
  enable: true
  message: "&b%player_name% &eSalio del servidor!"
