channels:
  global:
    default: true
    format: "%vault_prefix% &f%player_name% &7>"
    color: "&7"
    permission: "none"
    autoJoin: true
    aliases:
      - "globalchannel"
      - "global"
      - "g"
  vip:
    default: false
    format: "&e&lVIP &c&l| &f%player_name% &7>"
    color: "&e"
    permission: "magicchat.channels.vip"
    autoJoin: true
    aliases:
      - "vipchannel"
      - "vc"
  staff:
    default: false
    format: "&4&lSTAFF &c&l| &f%player_name% &7>"
    color: "&b"
    permission: "magicchat.channels.staff"
    autoJoin: true
    aliases:
      - "staffchannel"
      - "sc"
joinMessage:
  enable: true
  message: "&b%player_name% &eIngreso al servidor!"
quitMessage:
  enable: true
  message: "&b%player_name% &eSalio del servidor!"
